### ISSUE TITLE
readme for 2020 General Elections

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/erj-nc#1]
In [readme_nc_gen_20_prec.txt](https://redistrictingdatahub.org/wp-content/uploads/2022/02/readme_nc_gen_20_prec.txt) and [readme_nc_vest_20.txt](https://redistrictingdatahub.org/wp-content/uploads/2021/06/readme_nc_vest_20.txt), please correct:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Incorrect Candidate Code | Correct Candidate Code
-- | --
SL001DNIC | GSL001DNIC
GSL026OWRI | GSL026OLEE

</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Incorrect   Name | Correct Name
-- | --
Steven K. DiFiore | Steven J. DiFiore

</body>

</html>

**Comment by spencer-rdh** [comment]
Thanks for pointing this out. The READMEs have been corrected. The candidate code will remain GSL026OWRI, and the description is now "Other / Write-In" as independent and write-in candidates are grouped together by contest in our processing. In this instance, Lee was the only indepdent or write-in candidate for that contest.

**Comment by rootsmusic** [comment]
You're welcome @spencer-rdh.  Please also correct https://redistrictingdatahub.org/wp-content/uploads/2021/06/readme_nc_vest_20.txt

**Comment by spencer-rdh** [comment]
I corrected Steven K. DiFiore to Steven J. DiFiore in the VEST README this morning. Sometimes to see changes made to media files on WordPress you have to clear cache. Thanks, again!

**Comment by rootsmusic** [comment]
> the description is now "Other / Write-In"

Ok @spencer-rdh, I'd have preferred having the candidate's name in the description.  But it's a minor issue to be clear about who's defined by the candidate code.
